CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    keyword VARCHAR(200) NOT NULL,
    normalized_keyword VARCHAR(200) NOT NULL,
    category VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    analysis_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    last_analyzed_at TIMESTAMPTZ,
    last_snapshot_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_keywords_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_keywords_analysis_status CHECK (analysis_status IN ('PENDING','RUNNING','SUCCESS','FAILED','SKIPPED'))
);

ALTER TABLE keywords ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS keyword VARCHAR(200);
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS normalized_keyword VARCHAR(200);
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS analysis_status VARCHAR(30) NOT NULL DEFAULT 'PENDING';
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS last_analyzed_at TIMESTAMPTZ;
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS last_snapshot_date DATE;
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE keywords ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

DO $$
BEGIN
    IF to_regclass('public.keyword_master') IS NOT NULL THEN
        INSERT INTO keywords (
            id,
            user_id,
            keyword,
            normalized_keyword,
            category,
            active,
            analysis_status,
            last_analyzed_at,
            created_at,
            updated_at,
            deleted_at
        )
        SELECT
            id,
            user_id,
            keyword,
            normalized_keyword,
            category_code,
            status = 'ACTIVE',
            CASE analysis_status
                WHEN 'ANALYZED' THEN 'SUCCESS'
                ELSE analysis_status
            END,
            last_analyzed_at,
            created_at,
            updated_at,
            CASE
                WHEN status = 'DELETED' THEN COALESCE(updated_at, now())
                ELSE NULL
            END
        FROM keyword_master
        ON CONFLICT (id) DO NOTHING;

        PERFORM setval(
            pg_get_serial_sequence('keywords', 'id'),
            GREATEST((SELECT COALESCE(MAX(id), 1) FROM keywords), 1)
        );
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_keywords_user_normalized_active
    ON keywords(user_id, normalized_keyword)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_keywords_user_active ON keywords(user_id, active);
CREATE INDEX IF NOT EXISTS idx_keywords_last_analyzed_at ON keywords(last_analyzed_at);
CREATE INDEX IF NOT EXISTS idx_keywords_category ON keywords(category);
