CREATE TABLE IF NOT EXISTS shopping_search_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id BIGINT NOT NULL,
    search_date DATE NOT NULL,
    query VARCHAR(200) NOT NULL,
    sort_type VARCHAR(20) NOT NULL DEFAULT 'sim',
    display_count INT NOT NULL DEFAULT 100,
    total_count INT,
    min_price NUMERIC(14,2),
    max_price NUMERIC(14,2),
    avg_price NUMERIC(14,2),
    median_price NUMERIC(14,2),
    price_spread_rate NUMERIC(8,4),
    competition_level VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    api_cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'SUCCESS',
    error_message TEXT,
    raw_summary JSONB,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_shopping_snapshots_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id),
    CONSTRAINT ck_shopping_competition_level CHECK (competition_level IN ('UNKNOWN','LOW','MEDIUM','HIGH','VERY_HIGH')),
    CONSTRAINT ck_shopping_snapshot_status CHECK (status IN ('PENDING','RUNNING','SUCCESS','FAILED','SKIPPED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopping_snapshot_keyword_date_sort
    ON shopping_search_snapshots(keyword_id, search_date, sort_type);
CREATE INDEX IF NOT EXISTS idx_shopping_snapshots_search_date
    ON shopping_search_snapshots(search_date);
CREATE INDEX IF NOT EXISTS idx_shopping_snapshots_competition
    ON shopping_search_snapshots(competition_level);

CREATE TABLE IF NOT EXISTS shopping_item_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'NAVER_SHOPPING',
    source_product_id VARCHAR(100),
    rank_no INT NOT NULL,
    title_raw TEXT NOT NULL,
    title_clean TEXT,
    product_url TEXT NOT NULL,
    image_url TEXT,
    low_price NUMERIC(14,2),
    high_price NUMERIC(14,2),
    mall_name VARCHAR(200),
    brand VARCHAR(200),
    maker VARCHAR(200),
    category1 VARCHAR(100),
    category2 VARCHAR(100),
    category3 VARCHAR(100),
    category4 VARCHAR(100),
    raw_item JSONB,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_shopping_items_snapshot FOREIGN KEY (snapshot_id) REFERENCES shopping_search_snapshots(id),
    CONSTRAINT fk_shopping_items_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopping_item_snapshot_rank
    ON shopping_item_snapshots(snapshot_id, rank_no);
CREATE INDEX IF NOT EXISTS idx_shopping_items_keyword_price
    ON shopping_item_snapshots(keyword_id, low_price);
CREATE INDEX IF NOT EXISTS idx_shopping_items_source_product
    ON shopping_item_snapshots(source, source_product_id);
CREATE INDEX IF NOT EXISTS idx_shopping_items_category
    ON shopping_item_snapshots(category1, category2);

CREATE TABLE IF NOT EXISTS api_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    endpoint VARCHAR(200) NOT NULL,
    request_key VARCHAR(500),
    http_status INT,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    duration_ms INT,
    error_code VARCHAR(100),
    error_message TEXT,
    rate_limit_scope VARCHAR(100),
    called_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_api_call_logs_provider_called_at
    ON api_call_logs(provider, called_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_call_logs_success_called_at
    ON api_call_logs(success, called_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_call_logs_request_key
    ON api_call_logs(request_key);
