DO $$
BEGIN
    IF to_regclass('public.trend_snapshot') IS NOT NULL
       AND to_regclass('public.trend_snapshots') IS NULL THEN
        ALTER TABLE trend_snapshot RENAME TO trend_snapshots;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS trend_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    time_unit VARCHAR(20) NOT NULL,
    data_period DATE NOT NULL,
    ratio NUMERIC(10,4) NOT NULL,
    device VARCHAR(20) NOT NULL DEFAULT 'ALL',
    gender VARCHAR(20) NOT NULL DEFAULT 'ALL',
    ages VARCHAR(100) NOT NULL DEFAULT '',
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_trend_snapshots_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id),
    CONSTRAINT ck_trend_snapshots_time_unit CHECK (time_unit IN ('DATE','WEEK','MONTH'))
);

ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS snapshot_date DATE;
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS period_start DATE;
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS period_end DATE;
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS data_period DATE;
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS device VARCHAR(20) NOT NULL DEFAULT 'ALL';
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NOT NULL DEFAULT 'ALL';
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS ages VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE trend_snapshots ADD COLUMN IF NOT EXISTS raw_payload JSONB;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'trend_snapshots'
          AND column_name = 'period'
    ) THEN
        UPDATE trend_snapshots
        SET snapshot_date = COALESCE(snapshot_date, period),
            period_start = COALESCE(period_start, period),
            period_end = COALESCE(period_end, period),
            data_period = COALESCE(data_period, period)
        WHERE snapshot_date IS NULL
           OR period_start IS NULL
           OR period_end IS NULL
           OR data_period IS NULL;
    END IF;
END $$;

UPDATE trend_snapshots
SET snapshot_date = COALESCE(snapshot_date, CURRENT_DATE),
    period_start = COALESCE(period_start, snapshot_date, CURRENT_DATE),
    period_end = COALESCE(period_end, snapshot_date, CURRENT_DATE),
    data_period = COALESCE(data_period, snapshot_date, CURRENT_DATE),
    device = COALESCE(NULLIF(device, ''), 'ALL'),
    gender = COALESCE(NULLIF(gender, ''), 'ALL'),
    ages = COALESCE(ages, '');

ALTER TABLE trend_snapshots ALTER COLUMN snapshot_date SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN period_start SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN period_end SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN data_period SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN device SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN gender SET NOT NULL;
ALTER TABLE trend_snapshots ALTER COLUMN ages SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_trend_snapshots_keyword'
    ) THEN
        ALTER TABLE trend_snapshots
            ADD CONSTRAINT fk_trend_snapshots_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_trend_snapshots_time_unit'
    ) THEN
        ALTER TABLE trend_snapshots
            ADD CONSTRAINT ck_trend_snapshots_time_unit CHECK (time_unit IN ('DATE','WEEK','MONTH'));
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_trend_snapshot_keyword_date_period_time_unit_filter
    ON trend_snapshots (
        keyword_id,
        snapshot_date,
        time_unit,
        data_period,
        COALESCE(device, ''),
        COALESCE(gender, ''),
        COALESCE(ages, '')
    );
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_keyword_date
    ON trend_snapshots(keyword_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_data_period
    ON trend_snapshots(data_period);

CREATE TABLE IF NOT EXISTS batch_job_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(50) NOT NULL,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    target_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failure_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_batch_job_history_job_type CHECK (job_type IN ('SHOPPING_SEARCH_DAILY','DATALAB_TREND_DAILY','ALERT_GENERATE_DAILY')),
    CONSTRAINT ck_batch_job_history_trigger_type CHECK (trigger_type IN ('MANUAL','SCHEDULED')),
    CONSTRAINT ck_batch_job_history_status CHECK (status IN ('RUNNING','SUCCESS','PARTIAL_SUCCESS','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_batch_job_history_started_at
    ON batch_job_history(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_batch_job_history_job_type_status
    ON batch_job_history(job_type, status);
