DO $$
BEGIN
    IF to_regclass('public.wholesale_file') IS NOT NULL
       AND to_regclass('public.wholesale_uploads') IS NULL THEN
        ALTER TABLE wholesale_file RENAME TO wholesale_uploads;
    END IF;

    IF to_regclass('public.wholesale_product') IS NOT NULL
       AND to_regclass('public.wholesale_products') IS NULL THEN
        ALTER TABLE wholesale_product RENAME TO wholesale_products;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS wholesale_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_name VARCHAR(100),
    original_file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_type VARCHAR(20) NOT NULL DEFAULT 'CSV',
    requested_encoding VARCHAR(20) NOT NULL DEFAULT 'AUTO',
    detected_encoding VARCHAR(20) NOT NULL DEFAULT 'UTF_8',
    total_rows INT NOT NULL DEFAULT 0,
    success_rows INT NOT NULL DEFAULT 0,
    failed_rows INT NOT NULL DEFAULT 0,
    detected_columns TEXT,
    mapping_product_name VARCHAR(255),
    mapping_supply_price VARCHAR(255),
    mapping_shipping_fee VARCHAR(255),
    mapping_category VARCHAR(255),
    mapping_product_url VARCHAR(255),
    column_mapping JSONB,
    status VARCHAR(30) NOT NULL DEFAULT 'UPLOADED',
    error_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_wholesale_uploads_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_wholesale_uploads_status CHECK (status IN ('UPLOADED','MAPPED','PARSED','FAILED'))
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'original_filename'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'original_file_name'
    ) THEN
        ALTER TABLE wholesale_uploads RENAME COLUMN original_filename TO original_file_name;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'stored_path'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'file_path'
    ) THEN
        ALTER TABLE wholesale_uploads RENAME COLUMN stored_path TO file_path;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'row_count'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_uploads'
          AND column_name = 'total_rows'
    ) THEN
        ALTER TABLE wholesale_uploads RENAME COLUMN row_count TO total_rows;
    END IF;
END $$;

ALTER TABLE wholesale_uploads ADD COLUMN IF NOT EXISTS file_type VARCHAR(20) NOT NULL DEFAULT 'CSV';
ALTER TABLE wholesale_uploads ADD COLUMN IF NOT EXISTS success_rows INT NOT NULL DEFAULT 0;
ALTER TABLE wholesale_uploads ADD COLUMN IF NOT EXISTS failed_rows INT NOT NULL DEFAULT 0;
ALTER TABLE wholesale_uploads ADD COLUMN IF NOT EXISTS column_mapping JSONB;
ALTER TABLE wholesale_uploads ADD COLUMN IF NOT EXISTS error_summary TEXT;

CREATE INDEX IF NOT EXISTS idx_wholesale_uploads_user_created
    ON wholesale_uploads(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wholesale_uploads_status
    ON wholesale_uploads(status);

CREATE TABLE IF NOT EXISTS wholesale_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    row_no INT NOT NULL,
    source_name VARCHAR(100),
    external_product_id VARCHAR(200),
    product_name TEXT,
    normalized_product_name TEXT,
    supply_price NUMERIC(14,2),
    shipping_fee NUMERIC(14,2),
    image_url TEXT,
    product_url TEXT,
    category VARCHAR(200),
    brand VARCHAR(200),
    maker VARCHAR(200),
    option_name VARCHAR(300),
    stock_status VARCHAR(100),
    is_sold_out BOOLEAN NOT NULL DEFAULT FALSE,
    memo TEXT,
    parse_status VARCHAR(20) NOT NULL DEFAULT 'PARSED',
    error_message TEXT,
    raw_row JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_wholesale_products_upload FOREIGN KEY (upload_id) REFERENCES wholesale_uploads(id),
    CONSTRAINT fk_wholesale_products_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_wholesale_products_parse_status CHECK (parse_status IN ('PARSED','INVALID'))
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'file_id'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'upload_id'
    ) THEN
        ALTER TABLE wholesale_products RENAME COLUMN file_id TO upload_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'normalized_name'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'normalized_product_name'
    ) THEN
        ALTER TABLE wholesale_products RENAME COLUMN normalized_name TO normalized_product_name;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'source_category'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'wholesale_products'
          AND column_name = 'category'
    ) THEN
        ALTER TABLE wholesale_products RENAME COLUMN source_category TO category;
    END IF;
END $$;

ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS source_name VARCHAR(100);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS external_product_id VARCHAR(200);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS brand VARCHAR(200);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS maker VARCHAR(200);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS option_name VARCHAR(300);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS stock_status VARCHAR(100);
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS is_sold_out BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS memo TEXT;
ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS raw_row JSONB;

UPDATE wholesale_products product
SET user_id = upload.user_id,
    source_name = COALESCE(product.source_name, upload.source_name)
FROM wholesale_uploads upload
WHERE product.upload_id = upload.id
  AND (product.user_id IS NULL OR product.source_name IS NULL);

UPDATE wholesale_products
SET is_sold_out = FALSE
WHERE is_sold_out IS NULL;

ALTER TABLE wholesale_products ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE wholesale_products ALTER COLUMN is_sold_out SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_wholesale_products_upload'
    ) THEN
        ALTER TABLE wholesale_products
            ADD CONSTRAINT fk_wholesale_products_upload FOREIGN KEY (upload_id) REFERENCES wholesale_uploads(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_wholesale_products_user'
    ) THEN
        ALTER TABLE wholesale_products
            ADD CONSTRAINT fk_wholesale_products_user FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_wholesale_products_parse_status'
    ) THEN
        ALTER TABLE wholesale_products
            ADD CONSTRAINT ck_wholesale_products_parse_status CHECK (parse_status IN ('PARSED','INVALID'));
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_wholesale_products_upload_row
    ON wholesale_products(upload_id, row_no);
CREATE INDEX IF NOT EXISTS idx_wholesale_products_user_source
    ON wholesale_products(user_id, source_name);
CREATE INDEX IF NOT EXISTS idx_wholesale_products_price
    ON wholesale_products(supply_price);
CREATE INDEX IF NOT EXISTS idx_wholesale_products_category
    ON wholesale_products(category);
