CREATE TABLE IF NOT EXISTS alert_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    min_score INT NOT NULL DEFAULT 0,
    min_margin_rate NUMERIC(6,2) NOT NULL DEFAULT 0,
    category_codes TEXT NOT NULL DEFAULT '',
    risk_excluded BOOLEAN NOT NULL DEFAULT TRUE,
    frequency VARCHAR(30) NOT NULL DEFAULT 'DAILY_SUMMARY',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_alert_rule_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_alert_rule_min_score CHECK (min_score >= 0 AND min_score <= 100),
    CONSTRAINT ck_alert_rule_min_margin_rate CHECK (min_margin_rate >= 0),
    CONSTRAINT ck_alert_rule_frequency CHECK (frequency IN ('DAILY_SUMMARY','WEEKLY_SUMMARY'))
);

CREATE INDEX IF NOT EXISTS idx_alert_rule_user_active
    ON alert_rule(user_id, active);
CREATE INDEX IF NOT EXISTS idx_alert_rule_active
    ON alert_rule(active);

CREATE TABLE IF NOT EXISTS alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    CONSTRAINT fk_alert_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_alert_rule FOREIGN KEY (rule_id) REFERENCES alert_rule(id),
    CONSTRAINT ck_alert_type CHECK (type IN ('CANDIDATE_SCORE')),
    CONSTRAINT ck_alert_status CHECK (status IN ('UNREAD','READ')),
    CONSTRAINT uk_alert_rule_candidate_type UNIQUE (rule_id, candidate_id, type)
);

DO $$
BEGIN
    IF to_regclass('public.product_candidate') IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM pg_constraint
           WHERE conname = 'fk_alert_candidate'
       ) THEN
        ALTER TABLE alert
            ADD CONSTRAINT fk_alert_candidate FOREIGN KEY (candidate_id) REFERENCES product_candidate(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_alert_user_created
    ON alert(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alert_user_status
    ON alert(user_id, status);
CREATE INDEX IF NOT EXISTS idx_alert_candidate
    ON alert(candidate_id);
