CREATE TABLE IF NOT EXISTS naver_store_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_name VARCHAR(200),
    store_id VARCHAR(100),
    seller_id VARCHAR(100),
    connection_status VARCHAR(30) NOT NULL DEFAULT 'DISCONNECTED',
    access_token_encrypted TEXT,
    refresh_token_encrypted TEXT,
    token_expires_at TIMESTAMPTZ,
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_store_connections_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_naver_store_connections_status
        CHECK (connection_status IN ('CONNECTED','EXPIRED','DISCONNECTED','ERROR'))
);

CREATE INDEX IF NOT EXISTS idx_naver_store_connections_user_status
    ON naver_store_connections(user_id, connection_status);
CREATE INDEX IF NOT EXISTS idx_naver_store_connections_last_synced
    ON naver_store_connections(last_synced_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_naver_store_connections_user_store
    ON naver_store_connections(user_id, store_id)
    WHERE store_id IS NOT NULL;
