CREATE TABLE IF NOT EXISTS naver_store_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    channel_product_no VARCHAR(100) NOT NULL,
    origin_product_no VARCHAR(100),
    product_name TEXT NOT NULL,
    sale_price NUMERIC(14,2) NOT NULL,
    sale_status VARCHAR(50) NOT NULL,
    image_url TEXT,
    category_name VARCHAR(300),
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_synced_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_store_products_connection FOREIGN KEY (connection_id) REFERENCES naver_store_connections(id),
    CONSTRAINT fk_naver_store_products_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_naver_store_products_connection_channel UNIQUE (connection_id, channel_product_no)
);

CREATE INDEX IF NOT EXISTS idx_naver_store_products_user
    ON naver_store_products(user_id);
CREATE INDEX IF NOT EXISTS idx_naver_store_products_connection
    ON naver_store_products(connection_id);
CREATE INDEX IF NOT EXISTS idx_naver_store_products_status
    ON naver_store_products(sale_status);
CREATE INDEX IF NOT EXISTS idx_naver_store_products_synced
    ON naver_store_products(last_synced_at DESC);

CREATE TABLE IF NOT EXISTS naver_store_product_sync_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    target_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failure_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_store_product_sync_histories_connection FOREIGN KEY (connection_id) REFERENCES naver_store_connections(id),
    CONSTRAINT fk_naver_store_product_sync_histories_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_naver_store_product_sync_histories_status
        CHECK (status IN ('RUNNING','SUCCESS','PARTIAL_SUCCESS','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_naver_store_product_sync_histories_user
    ON naver_store_product_sync_histories(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_naver_store_product_sync_histories_connection
    ON naver_store_product_sync_histories(connection_id, created_at DESC);
