CREATE TABLE IF NOT EXISTS store_product_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    wholesale_product_id BIGINT,
    purchase_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    shipping_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
    packaging_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
    extra_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    platform_fee_rate NUMERIC(6,2) NOT NULL DEFAULT 0,
    target_margin_rate NUMERIC(6,2) NOT NULL DEFAULT 25,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_store_product_costs_product FOREIGN KEY (store_product_id) REFERENCES naver_store_products(id),
    CONSTRAINT fk_store_product_costs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_store_product_costs_wholesale_product FOREIGN KEY (wholesale_product_id) REFERENCES wholesale_products(id),
    CONSTRAINT uk_store_product_costs_product UNIQUE (store_product_id),
    CONSTRAINT ck_store_product_costs_amounts CHECK (
        purchase_cost >= 0
        AND shipping_fee >= 0
        AND packaging_fee >= 0
        AND extra_cost >= 0
    ),
    CONSTRAINT ck_store_product_costs_rates CHECK (
        platform_fee_rate >= 0
        AND platform_fee_rate < 100
        AND target_margin_rate >= 0
        AND target_margin_rate < 100
    )
);

CREATE INDEX IF NOT EXISTS idx_store_product_costs_user
    ON store_product_costs(user_id);
CREATE INDEX IF NOT EXISTS idx_store_product_costs_wholesale_product
    ON store_product_costs(wholesale_product_id);
