CREATE TABLE IF NOT EXISTS naver_order_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_no VARCHAR(100) NOT NULL,
    product_order_no VARCHAR(100) NOT NULL,
    order_date TIMESTAMPTZ NOT NULL,
    payment_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    order_status VARCHAR(50) NOT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_order_snapshots_connection FOREIGN KEY (connection_id) REFERENCES naver_store_connections(id),
    CONSTRAINT fk_naver_order_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_naver_order_snapshots_product_order UNIQUE (connection_id, product_order_no)
);

CREATE INDEX IF NOT EXISTS idx_naver_order_snapshots_user_order_date
    ON naver_order_snapshots(user_id, order_date DESC);

CREATE TABLE IF NOT EXISTS naver_settlement_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    settlement_date DATE NOT NULL,
    product_order_no VARCHAR(100) NOT NULL,
    settlement_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_settlement_snapshots_connection FOREIGN KEY (connection_id) REFERENCES naver_store_connections(id),
    CONSTRAINT fk_naver_settlement_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_naver_settlement_snapshots_order_date UNIQUE (connection_id, settlement_date, product_order_no)
);

CREATE INDEX IF NOT EXISTS idx_naver_settlement_snapshots_user_date
    ON naver_settlement_snapshots(user_id, settlement_date DESC);

CREATE TABLE IF NOT EXISTS naver_commission_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    product_order_no VARCHAR(100) NOT NULL,
    commission_type VARCHAR(100) NOT NULL,
    commission_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_naver_commission_snapshots_connection FOREIGN KEY (connection_id) REFERENCES naver_store_connections(id),
    CONSTRAINT fk_naver_commission_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_naver_commission_snapshots_order_type UNIQUE (connection_id, base_date, product_order_no, commission_type)
);

CREATE INDEX IF NOT EXISTS idx_naver_commission_snapshots_user_date
    ON naver_commission_snapshots(user_id, base_date DESC);
