CREATE TABLE IF NOT EXISTS subscription_plan (
    code VARCHAR(20) PRIMARY KEY,
    display_name VARCHAR(50) NOT NULL,
    keyword_limit INT NOT NULL,
    csv_row_limit INT NOT NULL,
    candidate_limit INT NOT NULL,
    CONSTRAINT ck_subscription_plan_code CHECK (code IN ('FREE','BASIC','PRO')),
    CONSTRAINT ck_subscription_plan_limits CHECK (
        keyword_limit >= 0
        AND csv_row_limit >= 0
        AND candidate_limit >= 0
    )
);

CREATE TABLE IF NOT EXISTS user_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_code VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_subscription_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_subscription_plan FOREIGN KEY (plan_code) REFERENCES subscription_plan(code),
    CONSTRAINT ck_user_subscription_status CHECK (status IN ('ACTIVE','EXPIRED','CANCELED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_subscription_user
    ON user_subscription(user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscription_plan_status
    ON user_subscription(plan_code, status);

CREATE TABLE IF NOT EXISTS category_master (
    code VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_category_master_code CHECK (code IN (
        'CAR_ACCESSORY',
        'DESK_OFFICE',
        'HOME_STORAGE',
        'BATH_CLEANING',
        'TRAVEL_ORGANIZER',
        'PET_WALK_HYGIENE',
        'KITCHEN_STORAGE',
        'CAMPING_PICNIC',
        'HOME_TRAINING',
        'SEASONAL_LIVING'
    ))
);

CREATE INDEX IF NOT EXISTS idx_category_master_active_sort
    ON category_master(active, sort_order);

CREATE TABLE IF NOT EXISTS risk_category_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_keyword VARCHAR(100) NOT NULL,
    handling_type VARCHAR(20) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_risk_category_rule_handling_type CHECK (handling_type IN ('EXCLUDE','CAUTION'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_risk_category_rule_keyword
    ON risk_category_rule(risk_keyword);
CREATE INDEX IF NOT EXISTS idx_risk_category_rule_active_sort
    ON risk_category_rule(active, sort_order);

CREATE TABLE IF NOT EXISTS product_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    keyword_id BIGINT,
    wholesale_product_id BIGINT,
    source_type VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    expected_sale_price INT NOT NULL,
    supply_price INT,
    shipping_fee INT,
    expected_margin_rate NUMERIC(6,2) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_product_candidate_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_product_candidate_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id),
    CONSTRAINT ck_product_candidate_source_type CHECK (source_type IN ('KEYWORD','CSV','API')),
    CONSTRAINT ck_product_candidate_category_code CHECK (category_code IN (
        'CAR_ACCESSORY',
        'DESK_OFFICE',
        'HOME_STORAGE',
        'BATH_CLEANING',
        'TRAVEL_ORGANIZER',
        'PET_WALK_HYGIENE',
        'KITCHEN_STORAGE',
        'CAMPING_PICNIC',
        'HOME_TRAINING',
        'SEASONAL_LIVING'
    )),
    CONSTRAINT ck_product_candidate_grade CHECK (grade IN ('EXCLUDED','HOLD','REVIEW','RECOMMENDED')),
    CONSTRAINT ck_product_candidate_status CHECK (status IN ('ACTIVE','SAVED','EXCLUDED'))
);

CREATE INDEX IF NOT EXISTS idx_product_candidate_user_status_created
    ON product_candidate(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_candidate_keyword
    ON product_candidate(keyword_id);
CREATE INDEX IF NOT EXISTS idx_product_candidate_wholesale_product
    ON product_candidate(wholesale_product_id);

CREATE TABLE IF NOT EXISTS candidate_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    trend_score INT NOT NULL,
    competition_score INT NOT NULL,
    margin_score INT NOT NULL,
    price_band_score INT NOT NULL,
    supply_score INT NOT NULL,
    risk_penalty INT NOT NULL,
    overall_score INT NOT NULL,
    grade VARCHAR(20) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    reasons TEXT NOT NULL,
    warnings TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_candidate_score_candidate FOREIGN KEY (candidate_id) REFERENCES product_candidate(id),
    CONSTRAINT ck_candidate_score_grade CHECK (grade IN ('EXCLUDED','HOLD','REVIEW','RECOMMENDED')),
    CONSTRAINT ck_candidate_score_risk_level CHECK (risk_level IN ('LOW','CAUTION','EXCLUDED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_candidate_score_candidate
    ON candidate_score(candidate_id);
CREATE INDEX IF NOT EXISTS idx_candidate_score_overall
    ON candidate_score(overall_score DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_alert_candidate'
    ) THEN
        ALTER TABLE alert
            ADD CONSTRAINT fk_alert_candidate
            FOREIGN KEY (candidate_id) REFERENCES product_candidate(id);
    END IF;
END $$;
