CREATE TABLE IF NOT EXISTS auth_security_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    action VARCHAR(40) NOT NULL,
    subject_hash VARCHAR(64),
    network_hash VARCHAR(64),
    retry_after_seconds INT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_auth_security_events_type CHECK (event_type IN ('RATE_LIMITED')),
    CONSTRAINT ck_auth_security_events_action CHECK (action IN ('LOGIN','SIGNUP','PASSWORD_RESET')),
    CONSTRAINT ck_auth_security_events_retry CHECK (retry_after_seconds IS NULL OR retry_after_seconds > 0)
);

CREATE INDEX IF NOT EXISTS idx_auth_security_events_action_time
    ON auth_security_events(action, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_security_events_subject_time
    ON auth_security_events(subject_hash, occurred_at DESC)
    WHERE subject_hash IS NOT NULL;
